/home/liminyang/.pyenv/versions/3.6.8/envs/bluehex/bin/python -u pretrain_model_test_on_bluehex.py   \
    --training-set $1                             \
    --classifier $2                               \
    --seed $3                                     \
    --task binary                                 \
    --setting-name pretrain_$1                    \
    --mlp-hidden 2400-1200-1200                   \
    --mlp-lr 0.0001                               \
    --mlp-batch-size 32                           \
    --mlp-epochs 200                              \
    --mlp-dropout 0.2                             \
    --tree 1000                                   \
    --testing-time 2019-10,2020-09                \
    --retrain 0                                   \
    --quiet 0
